#!/bin/sh


# cut last 3 chars to remove the '.md'
n=3
file=$(echo $1 | sed "s/\(.*\).\{$n\}/\1/")

if [ $file ]; then
  cp before.html $file.html
  marked $file.md >> $file.html
  cat after.html >> $file.html
else
  echo please provide filename without extention. for example: ./convert modular
fi
